source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:parousya/Parousya-SAAS-iOS-SDK.git'
platform :ios, '10.0'

use_frameworks!

target 'iOS Example' do
  pod 'ParousyaSAASSDK', '0.1.9'
end

#To fix this issue https://github.com/CocoaPods/CocoaPods/issues/9775
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
